### ISSUE TITLE
你好，请教如下问题

### ISSUE THREAD

**Issue by paizhongxing** [PhantomGrapes/MGeo#3]
1、MGeo论文中似乎测评了GeoGlue的两个任务，ranking对应query-poi相关性任务，retrieval对应query-poi库召回任务，但是在ModelScope的网站没有放出query-poi库召回任务的模型，请问这个模型应该如何获得，我是否可以直接使用'damo/mgeo_backbone_chinese_base'底座，结合Retrieval.py来复现得到论文的结果呢？
2、’'damo/mgeo_backbone_chinese_base'‘这个底座是基于全国数据还是杭州数据呢

**Comment by PhantomGrapes** [comment]
Please use model and dataset in github to reproduce paper. Those in modelscope is a more general pretrained model serving more tasks. All our released models is based on Hangzhou.
