### ISSUE TITLE
Dataset Problem

### ISSUE THREAD

**Issue by Heisenberg-Yin** [PhantomGrapes/MGeo#4]
The recall data GeoTES-recall-test.json.zip download from https://modelscope.cn/datasets/damo/GeoGLUE/files does not provide pos_id. Can you provide the ground truth for the test querys?

**Comment by PhantomGrapes** [comment]
To reproduce paper result, please download https://drive.google.com/file/d/1KxN377_l-yNwsYBifS_o0f50tKBYNYj-/view?usp=sharing.
